# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nrfmicro_13
    shield: [jorne_left, jorne_right]
    name: "Jorne_Brass"
  - board: nrfmicro_13_52833
    shield: [jorne_left, jorne_right]
    name: ["Jorne_Alps", "Sporne"]
  - board: nrfmicro_13_52833
    shield: radpad
  - board: [jorian840_left, jorian840_right]
    name: ["Jorian840_Omron", "Jorian840_Cobalt"]
  - board: [skean_left, skean_right]
    name: ["Skean_T1", "Skean_Alps"]
  - board: [wenki44_left, wenki44_right]
